title: lucsj.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Lucsj.github.io
description:  Blog personnel de Luc S. contenant plein d'articles et de notes sur mes sujets favorits (recettes, informatique, sant√©, voyages)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: Lucsj
  instagram: 
  linkedin: 
  pinterest: 
  rss: https://blindhelp.github.io/feed.xml
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: Lucsj-github-io-1
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile.lock
- LICENSE
- README.md
- CNAME
authors:
  Lucsj:
    name: Lucsj
    display_name: Luc S.
    web: https://blindhelp.github.io/lucsj

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
